name: Contents Map Generator

on:
  push:
    paths-ignore: 
      - '.github/**'

jobs:
  create-Contents-map:
    runs-on: ubuntu-latest  # ubuntu 최신버전에서 실행
    steps:
      - uses: actions/checkout@v3 # contents 브랜치 체크아웃

      - name: Set up Python # 파이썬 3.7버전 설치
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: checkout `gh-pages brench` # gh-pages 브랜치를 gh-pages 디렉토리에 체크아웃
        uses: actions/checkout@v3 
        with:
          ref: gh-pages
          path: gh-pages

      - name: Run ContentsMapGenerator.py # ContentsMap.json 생성
        run: |
          ls -al
          python ContentsMapGenerator.py "./gh-pages/"
          cd ./gh-pages/
          ls -al

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: gh-pages