name: Posts Map Generator
# PostsMapGenerator는 Posts 브랜치가 변경될 때 마다 실행되고
# PostsMapGenerator에서 생성된 postsmap.json은 develop 브랜치에 배포되고
# develop 브랜치가 변경될 때 마다 실행되는 deploy는 blazorwasm을 재 빌드함.

on:
  push:
    branches: 
      - 'posts'
    paths-ignore: 
      - '.github/**'

jobs:
  create-posts-map:
    runs-on: ubuntu-latest  # ubuntu 최신버전에서 실행
    steps:
      - uses: actions/checkout@v3 # posts 브랜치 체크아웃

      - name: Set up Python # 파이썬 3.7버전 설치
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: checkout `develop brench` # develop 브랜치를 develop 디렉토리에 체크아웃
        uses: actions/checkout@v3 
        with:
          ref: develop
          path: develop

      - name: checkout `gh-pages brench` # gh-pages 브랜치를 gh-pages 디렉토리에 체크아웃
        uses: actions/checkout@v3 
        with:
          ref: gh-pages
          path: gh-pages

      - name: Run PostMapGenerator # postsmap.json 생성
        run: |
          ls -al
          python develop/PostsMapGenerator.py "./gh-pages/"

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages
          FOLDER: gh-pages